name: "build and publish app"

on:
  workflow_dispatch:

jobs:
  publish-app:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: checkout code
        uses: actions/checkout@v7

      - name: install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: app/pnpm-lock.yaml

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: install frontend dependencies
        run: cd app && pnpm install

      - name: build app
        uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "CLT-Demo Rev v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          args: ${{ matrix.args }}
